/**
 * Foxit eSign testLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core';
import {
  EmailGroupIdentifiers,
  emailGroupIdentifiersSchema,
} from '../models/emailGroupIdentifiers';
import { unknown } from '../schema';
import { BaseController } from './baseController';

export class PartiesAPIController extends BaseController {
  /**
   * To create a new email group via API, please make a call to parties/createEmailGroup with the
   * following parameters.
   *
   * You can only pass up to 20 party details.
   *
   * @param body
   * @return Response from the API call
   */
  async createEmailGroup(
    body: unknown,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<unknown>> {
    const req = this.createRequest('POST', '/parties/createEmailGroup');
    const mapped = req.prepareArgs({ body: [body, unknown()] });
    req.json(mapped.body);
    return req.callAsJson(unknown(), requestOptions);
  }

  /**
   * You can pool our API to get email group information.
   *
   * You can pass this request with no parameters to get the details of all of the email groups in your
   * account.
   *
   * @param body
   * @return Response from the API call
   */
  async getEmailGroupDetails(
    body: EmailGroupIdentifiers,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<unknown>> {
    const req = this.createRequest('POST', '/parties/getEmailGroups');
    const mapped = req.prepareArgs({
      body: [body, emailGroupIdentifiersSchema],
    });
    req.json(mapped.body);
    return req.callAsJson(unknown(), requestOptions);
  }
}
