/**
 * Foxit eSign testLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

/** The company object leveraged when providing details about the company of a new account. */
export interface AccountCreationCompanyObject {
  /** Name of company account to be created in Foxit eSign */
  companyName: string;
  /** The address of the company to be created */
  companyAddress: string;
}

export const accountCreationCompanyObjectSchema: Schema<AccountCreationCompanyObject> = object(
  {
    companyName: ['companyName', string()],
    companyAddress: ['companyAddress', string()],
  }
);
