/**
 * Foxit eSign testLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

/** The user object leveraged when providing details about the main user of a new account. */
export interface AccountCreationUserObject {
  /** First name of the account user */
  firstName: string;
  /** Last name of account user */
  lastName: string;
  /** Email address of account user */
  emailId: string;
  /** The initial password for this user, it can be combination of Uppercase/Lowercase letters, numbers and special characters */
  loginPassword: string;
}

export const accountCreationUserObjectSchema: Schema<AccountCreationUserObject> = object(
  {
    firstName: ['firstName', string()],
    lastName: ['lastName', string()],
    emailId: ['emailId', string()],
    loginPassword: ['loginPassword', string()],
  }
);
