/**
 * Foxit eSign testLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  object,
  optional,
  Schema,
  string,
  unknown,
} from '../schema';
import { Party, partySchema } from './party';

/** A folder meant to be used when sending URLs */
export interface BaseFolder {
  /** Name of the document(s) folder */
  folderName: string;
  parties: Party[];
  fields: unknown[];
  /** Use this field to send the folder to the recipient parties. Each party will then receive a unique link in their email to sign the document. The invitation mail and subject in this case will be the same as the default invitation mail setup in your account. */
  sendNow?: boolean;
  createEmbeddedSigningSession: string;
  createEmbeddedSigningSessionForAllParties: string;
}

export const baseFolderSchema: Schema<BaseFolder> = object({
  folderName: ['folderName', string()],
  parties: ['parties', array(lazy(() => partySchema))],
  fields: ['fields', array(unknown())],
  sendNow: ['sendNow', optional(boolean())],
  createEmbeddedSigningSession: ['createEmbeddedSigningSession', string()],
  createEmbeddedSigningSessionForAllParties: [
    'createEmbeddedSigningSessionForAllParties',
    string(),
  ],
});
