/**
 * Foxit eSign testLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface DependentField1 {
  dependentFieldName: string;
  parentFieldName: string;
  parentFieldValue: string;
  options: string;
}

export const dependentField1Schema: Schema<DependentField1> = object({
  dependentFieldName: ['dependentFieldName', string()],
  parentFieldName: ['parentFieldName', string()],
  parentFieldValue: ['parentFieldValue', string()],
  options: ['options', string()],
});
