/**
 * Foxit eSign testLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, object, Schema, string } from '../schema';

export interface EmailGroupIdentifiers {
  emailGroupNames: string[];
}

export const emailGroupIdentifiersSchema: Schema<EmailGroupIdentifiers> = object(
  { emailGroupNames: ['emailGroupNames', array(string())] }
);
