/**
 * Foxit eSign testLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface EmailGroupParty {
  firstName: string;
  lastName: string;
  emailId: string;
}

export const emailGroupPartySchema: Schema<EmailGroupParty> = object({
  firstName: ['firstName', string()],
  lastName: ['lastName', string()],
  emailId: ['emailId', string()],
});
