/**
 * Foxit eSign testLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  number,
  object,
  optional,
  Schema,
} from '../schema';
import { Party, partySchema } from './party';

export interface EnvelopeRecipientsUpdate {
  folderId: number;
  /** Choose whether to validate the email address of the recipients. */
  allowAdvancedEmailValidation?: boolean;
  parties: Party[];
}

export const envelopeRecipientsUpdateSchema: Schema<EnvelopeRecipientsUpdate> = object(
  {
    folderId: ['folderId', number()],
    allowAdvancedEmailValidation: [
      'allowAdvancedEmailValidation',
      optional(boolean()),
    ],
    parties: ['parties', array(lazy(() => partySchema))],
  }
);
