/**
 * Foxit eSign testLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, Schema } from '../schema';

export interface EnvelopeIdentifier {
  folderId: number;
}

export const envelopeIdentifierSchema: Schema<EnvelopeIdentifier> = object({
  folderId: ['folderId', number()],
});
