/**
 * Foxit eSign testLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, number, object, optional, Schema, unknown } from '../schema';
import { CustomField, customFieldSchema } from './customField';

export interface EnvelopeFieldsUpdate {
  folderId: number;
  customField1?: CustomField;
  customField2?: CustomField;
  fields?: unknown;
}

export const envelopeFieldsUpdateSchema: Schema<EnvelopeFieldsUpdate> = object({
  folderId: ['folderId', number()],
  customField1: ['custom_field1', optional(lazy(() => customFieldSchema))],
  customField2: ['custom_field2', optional(lazy(() => customFieldSchema))],
  fields: ['fields', unknown()],
});
