/**
 * Foxit eSign testLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, number, object, optional, Schema, string } from '../schema';

export interface Field1 {
  type: string;
  x: number;
  y: number;
  width: number;
  height: number;
  pageNumber: number;
  tabOrder?: number;
  party: number;
  name?: string;
  tooltip?: string;
  value?: string;
  required?: boolean;
  characterLimit?: number;
  fontSize?: number;
  fontColor?: string;
  validation?: string;
}

export const field1Schema: Schema<Field1> = object({
  type: ['type', string()],
  x: ['x', number()],
  y: ['y', number()],
  width: ['width', number()],
  height: ['height', number()],
  pageNumber: ['pageNumber', number()],
  tabOrder: ['tabOrder', optional(number())],
  party: ['party', number()],
  name: ['name', optional(string())],
  tooltip: ['tooltip', optional(string())],
  value: ['value', optional(string())],
  required: ['required', optional(boolean())],
  characterLimit: ['characterLimit', optional(number())],
  fontSize: ['fontSize', optional(number())],
  fontColor: ['fontColor', optional(string())],
  validation: ['validation', optional(string())],
});
