/**
 * Foxit eSign testLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  nullable,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema';

export interface Field {
  type?: string;
  x?: number;
  y?: number;
  width?: number;
  height?: number;
  pageNumber?: number;
  documentNumber?: number;
  hideFieldNameForRecipients?: boolean;
  name?: string;
  tooltip?: string;
  value?: string;
  required?: boolean;
  characterLimit?: number;
  party?: number;
  fontSize?: number;
  fontColor?: string;
  options?: string[];
  tabOrder?: number;
  group?: string | null;
  multicheck?: boolean;
  checked?: boolean;
  hideCheckboxBorder?: boolean;
  dateFormat?: string;
}

export const fieldSchema: Schema<Field> = object({
  type: ['type', optional(string())],
  x: ['x', optional(number())],
  y: ['y', optional(number())],
  width: ['width', optional(number())],
  height: ['height', optional(number())],
  pageNumber: ['pageNumber', optional(number())],
  documentNumber: ['documentNumber', optional(number())],
  hideFieldNameForRecipients: [
    'hideFieldNameForRecipients',
    optional(boolean()),
  ],
  name: ['name', optional(string())],
  tooltip: ['tooltip', optional(string())],
  value: ['value', optional(string())],
  required: ['required', optional(boolean())],
  characterLimit: ['characterLimit', optional(number())],
  party: ['party', optional(number())],
  fontSize: ['fontSize', optional(number())],
  fontColor: ['fontColor', optional(string())],
  options: ['options', optional(array(string()))],
  tabOrder: ['tabOrder', optional(number())],
  group: ['group', optional(nullable(string()))],
  multicheck: ['multicheck', optional(boolean())],
  checked: ['checked', optional(boolean())],
  hideCheckboxBorder: ['hideCheckboxBorder', optional(boolean())],
  dateFormat: ['dateFormat', optional(string())],
});
