/**
 * Foxit eSign testLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for GrantTypeEnum
 */
export enum GrantTypeEnum {
  ClientCredentials = 'client_credentials',
}

/**
 * Schema for GrantTypeEnum
 */
export const grantTypeEnumSchema: Schema<GrantTypeEnum> = stringEnum(GrantTypeEnum);
