/**
 * Foxit eSign testLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for InputTypeEnum
 */
export enum InputTypeEnum {
  Url = 'url',
  Base64 = 'base64',
}

/**
 * Schema for InputTypeEnum
 */
export const inputTypeEnumSchema: Schema<InputTypeEnum> = stringEnum(InputTypeEnum);
