/**
 * Foxit eSign testLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, Schema, string } from '../schema';

export interface Party1 {
  permission: string;
  sequence: number;
  partyRole: string;
}

export const party1Schema: Schema<Party1> = object({
  permission: ['permission', string()],
  sequence: ['sequence', number()],
  partyRole: ['partyRole', string()],
});
