/**
 * Foxit eSign testLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, number, object, optional, Schema, string } from '../schema';

export interface Party2 {
  firstName: string;
  lastName: string;
  emailId: string;
  permission: string;
  workflowSequence: number;
  sequence: number;
  hostEmailId: string;
  allowNameChange: boolean;
  dialingCode?: string;
  signerAuthLevel: string;
  userDefinedAccessCode?: string;
}

export const party2Schema: Schema<Party2> = object({
  firstName: ['firstName', string()],
  lastName: ['lastName', string()],
  emailId: ['emailId', string()],
  permission: ['permission', string()],
  workflowSequence: ['workflowSequence', number()],
  sequence: ['sequence', number()],
  hostEmailId: ['hostEmailId', string()],
  allowNameChange: ['allowNameChange', boolean()],
  dialingCode: ['dialingCode', optional(string())],
  signerAuthLevel: ['signerAuthLevel', string()],
  userDefinedAccessCode: ['userDefinedAccessCode', optional(string())],
});
