/**
 * Foxit eSign testLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for PermissionsEnum
 */
export enum PermissionsEnum {
  FILLFIELDSANDSIGN = 'FILL_FIELDS_AND_SIGN',
  FILLFIELDSONLY = 'FILL_FIELDS_ONLY',
  SIGNONLY = 'SIGN_ONLY',
  VIEWONLY = 'VIEW_ONLY',
  PARTYASSIGNER = 'PARTY_ASSIGNER',
}

/**
 * Schema for PermissionsEnum
 */
export const permissionsEnumSchema: Schema<PermissionsEnum> = stringEnum(PermissionsEnum);
