/**
 * Foxit eSign testLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';
import {
  EnvelopeStatusEnum,
  envelopeStatusEnumSchema,
} from './envelopeStatusEnum';

/** The optional filters that a report may leverage */
export interface Report {
  /** Download data by the folder status. Status parameter can have any of the following values: EXECUTED,SHARED,DRAFT, PARTIALLY SIGNED, CANCELLED, EXPIRED and DELETED. */
  status: EnvelopeStatusEnum;
  /** Start of the Creation Date range. Accepted format: YYYY-MM-DD. */
  creationDateFrom: string;
  /** End of the Creation Date range. Accepted format: YYYY-MM-DD. */
  creationDateTo: string;
  /** Any folder which contains this string. */
  folderName?: string;
  /** Including folder fields in report. */
  includeFields?: string;
  /** Author email in report. */
  authorEmail?: string;
  /** Signer email in report. */
  signerEmail?: string;
}

export const reportSchema: Schema<Report> = object({
  status: ['status', envelopeStatusEnumSchema],
  creationDateFrom: ['creationDateFrom', string()],
  creationDateTo: ['creationDateTo', string()],
  folderName: ['folderName', optional(string())],
  includeFields: ['includeFields', optional(string())],
  authorEmail: ['authorEmail', optional(string())],
  signerEmail: ['signerEmail', optional(string())],
});
