/**
 * Foxit eSign testLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for ScopeEnum
 */
export enum ScopeEnum {
  Readwrite = 'read-write',
}

/**
 * Schema for ScopeEnum
 */
export const scopeEnumSchema: Schema<ScopeEnum> = stringEnum(ScopeEnum);
