/**
 * Foxit eSign testLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';

export interface SessionGeneration {
  /** Folder id you want to use to regenerate the expired folder embedded signing token for this folder. You can determine the folder id from the folder URL. */
  folderId: number;
  /** Recipient email id you want to use to regenerate the expired folder embedded signing token for this folder. */
  emailId: string;
  /** Recipient party id you want to use to regenerate the expired folder embedded signing token for this folder. */
  partyId?: string;
  /** Use this field to initiate the expiration of the embedded signing session. */
  sessionExpire?: string;
  /** Use this field to enter the time duration in milliseconds of the expiry on the embedded signing session. *Note*: required if `sessionExpire` is `true` */
  expiry?: string;
}

export const sessionGenerationSchema: Schema<SessionGeneration> = object({
  folderId: ['folderId', number()],
  emailId: ['emailId', string()],
  partyId: ['partyId', optional(string())],
  sessionExpire: ['sessionExpire', optional(string())],
  expiry: ['expiry', optional(string())],
});
