/**
 * Foxit eSign testLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for SignerAuthLevelsEnum
 */
export enum SignerAuthLevelsEnum {
  NO = 'NO',
  EnumSMSLINK = 'SMS LINK',
  EnumEmailAccessCode = 'Email Access Code',
  EnumSMSAccessCode = 'SMS Access Code',
  EnumVoiceAccessCode = 'Voice Access Code',
  EnumUserdefinedAccessCode = 'User-defined Access Code',
}

/**
 * Schema for SignerAuthLevelsEnum
 */
export const signerAuthLevelsEnumSchema: Schema<SignerAuthLevelsEnum> = stringEnum(SignerAuthLevelsEnum);
