/**
 * Foxit eSign testLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, Schema } from '../schema';
import { TemplateParty, templatePartySchema } from './templateParty';

/** Template's party roles and permission */
export interface TemplateParties {
  parties: TemplateParty[];
}

export const templatePartiesSchema: Schema<TemplateParties> = object({
  parties: ['parties', array(lazy(() => templatePartySchema))],
});
