/**
 * Foxit eSign testLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, number, object, Schema } from '../schema';

export interface TemplateIdentifiers {
  templateIds: number[];
}

export const templateIdentifiersSchema: Schema<TemplateIdentifiers> = object({
  templateIds: ['templateIds', array(number())],
});
