/**
 * Foxit eSign testLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, object, optional, Schema, string } from '../schema';
import { UserRolesEnum, userRolesEnumSchema } from './userRolesEnum';

/** The parameters used to create a user */
export interface UserCreation {
  /** First name of the account user */
  firstName: string;
  /** Last name of account user */
  lastName: string;
  /** Email address of account user */
  emailId: string;
  userRole: UserRolesEnum;
  /** Choose whether to activate this account immediately on creation */
  active: boolean;
  /** Choose whether to send the user an email to reset his password upon user creation */
  sendMailForPasswordReset: boolean;
  /** Choose whether to validate the user's email address when creating this account */
  allowAdvancedEmailValidation?: boolean;
  /** The location of this account user */
  address?: string;
  /** Department of the user */
  department?: string;
  /** Designation/Title of account user */
  title?: string;
  /** The ID of one of the Admins or Super-Admins from your account, which will act as manager for this user */
  managerId?: string;
  /** The initial  password for this user, it can be combination of Uppercase/Lowercase letters, numbers and special characters */
  loginPassword?: string;
}

export const userCreationSchema: Schema<UserCreation> = object({
  firstName: ['firstName', string()],
  lastName: ['lastName', string()],
  emailId: ['emailId', string()],
  userRole: ['userRole', userRolesEnumSchema],
  active: ['active', boolean()],
  sendMailForPasswordReset: ['sendMailForPasswordReset', boolean()],
  allowAdvancedEmailValidation: [
    'allowAdvancedEmailValidation',
    optional(boolean()),
  ],
  address: ['address', optional(string())],
  department: ['department', optional(string())],
  title: ['title', optional(string())],
  managerId: ['managerId', optional(string())],
  loginPassword: ['loginPassword', optional(string())],
});
