/**
 * Foxit eSign testLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for UserRolesEnum
 */
export enum UserRolesEnum {
  User = 'user',
  Admin = 'admin',
  SuperAdmin = 'super_admin',
}

/**
 * Schema for UserRolesEnum
 */
export const userRolesEnumSchema: Schema<UserRolesEnum> = stringEnum(UserRolesEnum);
