/**
 * Foxit eSign testLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema } from '../schema';
import { UserUpdate, userUpdateSchema } from './userUpdate';

/** The generic object for Updating a User */
export interface UserUpdateObject {
  user: UserUpdate;
}

export const userUpdateObjectSchema: Schema<UserUpdateObject> = object({
  user: ['user', lazy(() => userUpdateSchema)],
});
