/**
 * Foxit eSign testLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, object, optional, Schema, string } from '../schema';
import { UserRolesEnum, userRolesEnumSchema } from './userRolesEnum';

/** The parameters used to update a user */
export interface UserUpdate {
  /** the unique party id for the user to be updated */
  partyId: string;
  /** First name of the account user */
  firstName: string;
  /** Last name of account user */
  lastName: string;
  userRole: UserRolesEnum;
  /** Choose whether to activate this account immediately on creation */
  active: boolean;
  /** The location of this account user */
  address?: string;
  /** Department of the user */
  department?: string;
  /** Designation/Title of account user */
  title?: string;
  /** The ID of one of the Admins or Super-Admins from your account, which will act as manager for this user */
  managerId?: string;
}

export const userUpdateSchema: Schema<UserUpdate> = object({
  partyId: ['partyId', string()],
  firstName: ['firstName', string()],
  lastName: ['lastName', string()],
  userRole: ['userRole', userRolesEnumSchema],
  active: ['active', boolean()],
  address: ['address', optional(string())],
  department: ['department', optional(string())],
  title: ['title', optional(string())],
  managerId: ['managerId', optional(string())],
});
