/**
 * Foxit eSign testLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, number, object, Schema } from '../schema';

export interface WebhookIdentifiers {
  channelIds: number[];
}

export const webhookIdentifiersSchema: Schema<WebhookIdentifiers> = object({
  channelIds: ['channelIds', array(number())],
});
