/**
 * Foxit eSign testLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, object, optional, Schema } from '../schema';

export interface WebhookEvents {
  /** When a document folder is sent via web and webhook channel set as “Account” level, Foxit eSign calls your webhook URL with this event information. */
  folderSent?: boolean;
  /** When party open this document folder via email or embeddedSession URL, Foxit eSign calls your Webhook with this event information. */
  folderViewed?: boolean;
  /** When party signs this document folder, Foxit eSign calls your Webhook with this event information. */
  folderSigned?: boolean;
  /** When party canceled this document folder than Foxit eSign calls your Webhook with this event information. */
  folderCancelled?: boolean;
  /** When all party signed this document folder, Foxit eSign calls your Webhook with this event information. */
  folderExecuted?: boolean;
  /** When party canceled this document folder, Foxit eSign calls your Webhook with this event information. */
  folderDeleted?: boolean;
}

export const webhookEventsSchema: Schema<WebhookEvents> = object({
  folderSent: ['folder_sent', optional(boolean())],
  folderViewed: ['folder_viewed', optional(boolean())],
  folderSigned: ['folder_signed', optional(boolean())],
  folderCancelled: ['folder_cancelled', optional(boolean())],
  folderExecuted: ['folder_executed', optional(boolean())],
  folderDeleted: ['folder_deleted', optional(boolean())],
});
